import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  FileText,
  Send,
  ShieldCheck,
} from 'lucide-react';
import { useApplication, APP_STATUS } from '../context/ApplicationContext';
import { chatAPI } from '../services/api';

const USER_ID = 'frontend_user';

function Consent() {
  const navigate = useNavigate();
  const {
    application,
    documents,
    backendResponse,
    setConsent,
    setAppStatus,
    addMessage,
    addActivity,
    applyBackendResponse,
  } = useApplication();

  const [agreed, setAgreed] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const serviceName =
    application?.service || backendResponse?.service_name || 'Income Certificate';

  const handleApprove = async () => {
    if (!agreed) return;

    setSubmitting(true);
    setError('');
    setConsent('granted');
    setAppStatus(APP_STATUS.SUBMITTING);
    addActivity('USER', 'Explicit submission consent granted');
    addMessage('user', 'Yes, submit the application.');

    try {
      const response = await chatAPI.send({
        userId: USER_ID,
        message: 'Yes, submit the application.',
      });

      const data = response.data;
      applyBackendResponse(data);

      if (data.message) {
        addMessage('agent', data.message);
      }

      if (data.application_status === 'SUBMITTED' && data.application_id) {
        addActivity('SYSTEM', `Application submitted: ${data.application_id}`);
        navigate('/portal');
      } else if (data.escalated) {
        setError(
          data.message ||
            'The application could not be submitted and has been escalated.'
        );
      } else {
        navigate('/agent');
      }
    } catch (err) {
      setError(
        err.response?.data?.detail ||
          err.response?.data?.message ||
          'Submission failed. Please return to the agent.'
      );
      addActivity('SYSTEM', 'Submission request failed');
      setAppStatus(APP_STATUS.HUMAN_ESCALATION);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#f4f6f9]">
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-6 py-5 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-primary">Submission Consent</h1>
            <p className="text-sm text-gray-500 mt-1">
              Your confirmation is required before submission.
            </p>
          </div>
          <button
            onClick={() => navigate('/review')}
            className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 border border-gray-300 rounded-lg px-4 py-2"
          >
            <ArrowLeft size={14} /> Review
          </button>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5 mb-6 flex gap-3">
          <ShieldCheck className="text-blue-600 flex-shrink-0" size={21} />
          <div>
            <p className="font-semibold text-blue-900">No automatic submission</p>
            <p className="text-sm text-blue-700 mt-1">
              Aavedan+ will call the backend submission workflow only after you explicitly approve it.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-6 mb-6">
          <h2 className="font-bold text-gray-900 mb-5">Submission summary</h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Info label="Service" value={serviceName} />
            <Info label="Application ID" value={application?.id || 'Generated by backend on successful submission'} />
            <Info label="Documents" value={`${documents.length} document(s) provided`} />
            <Info label="Backend status" value={backendResponse?.application_status || 'Ready'} />
          </div>
        </div>

        <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-6 mb-6">
          <div className="flex gap-3">
            <AlertTriangle className="text-amber-600 flex-shrink-0" size={20} />
            <div>
              <h2 className="font-bold text-amber-900">Explicit consent required</h2>
              <p className="text-sm text-amber-800 mt-1">
                By checking this box, you authorise Aavedan+ to submit this application to the configured mock government portal.
              </p>
            </div>
          </div>

          <label className="mt-5 flex items-start gap-3 p-4 bg-white rounded-xl border border-amber-200 cursor-pointer">
            <input
              type="checkbox"
              checked={agreed}
              onChange={(event) => setAgreed(event.target.checked)}
              className="mt-1 w-5 h-5 accent-blue-600"
            />
            <span className="text-sm text-gray-700 leading-relaxed">
              I have reviewed the application and documents and explicitly consent to submission.
            </span>
          </label>
        </div>

        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 text-sm">
            {error}
          </div>
        )}

        <div className="flex justify-end">
          <button
            onClick={handleApprove}
            disabled={!agreed || submitting}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-blue-600 text-white font-semibold disabled:bg-gray-200 disabled:text-gray-400"
          >
            {submitting ? 'Submitting...' : 'Approve & Submit'}
            {!submitting && <Send size={18} />}
          </button>
        </div>
      </main>
    </div>
  );
}

function Info({ label, value }) {
  return (
    <div className="rounded-xl bg-gray-50 border border-gray-100 p-4">
      <p className="text-xs uppercase tracking-wide text-gray-500">{label}</p>
      <p className="text-sm font-semibold text-gray-800 mt-1">{value}</p>
    </div>
  );
}

export default Consent;
